# Generated by Django 4.2.7 on 2023-12-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0015_car_quantity'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bought_cars',
            field=models.ManyToManyField(blank=True, to='car_model.car'),
        ),
    ]
