# Generated by Django 4.2.7 on 2023-12-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_userprofile_bought_cars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
