# Generated by Django 4.2.7 on 2023-12-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
