# Generated by Django 4.2.7 on 2023-12-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_model', '0002_remove_brand_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
