# Generated by Django 4.2.7 on 2023-12-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0007_remove_car_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='quantity',
        ),
    ]
