# Generated by Django 4.2.7 on 2023-12-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0010_car_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
