# Generated by Django 4.2.7 on 2023-12-21 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand_model', '0002_remove_brand_country'),
        ('car_model', '0012_alter_car_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='brand_model.brand'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
