# Generated by Django 4.2.7 on 2023-12-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0013_alter_car_brand_delete_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default='Some default value', max_length=255),
        ),
    ]
