# Generated by Django 4.2.7 on 2023-12-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0014_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
