# Generated by Django 4.2.7 on 2023-12-26 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0003_alter_transaction_receiver_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='accounts.userbankaccount'),
        ),
    ]
